name: GOD MODE AI HUNTER QUANTUM v7

permissions:
  contents: write

on:

  schedule:
    - cron: '*/2 * * * *'

  workflow_dispatch:

jobs:

  run-bot:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install
      run: pip install requests

    - name: Run Hunter
      run: python main.py

    - name: Save memory
      run: |
        git config --global user.name "tracker"
        git config --global user.email "tracker@email.com"
        git add state.json || true
        git commit -m "update prices" || echo "No changes"
        git push
